CREATE TABLE IF NOT EXISTS words
(
    id INT PRIMARY KEY AUTO_INCREMENT,
    word VARCHAR(30) NOT NULL,
    input_time TIMESTAMP NOT NULL
);
CREATE TABLE IF NOT EXISTS images
(
    id INT PRIMARY KEY AUTO_INCREMENT,
     VARCHAR(30) NOT NULL,
    input_time TIMESTAMP NOT NULL
)